"""Initial schema.

Generated with `alembic revision --autogenerate` against the models in
`backend/database/models/`, then reviewed by hand. The review is not optional
ceremony: autogenerate produces DDL for whatever it finds, so anything wrong in
the models is faithfully written down here, and `--autogenerate` is not a reviewer.

Two hand-written bits:

1. **`import backend.database.base`.** The `UtcDateTime` columns are emitted as
   `backend.database.base.UtcDateTime(timezone=True)`, which is a *custom*
   `TypeDecorator`, not a `sa.` type. Autogenerate serialises the type by its
   qualified name and does not import it, so the generated file raises
   `NameError: name 'backend' is not defined` on the first `upgrade()`. Every
   future migration touching a timestamp needs this import too -- which is why it
   is here rather than being discovered by the first person to deploy.

2. **`batch_alter_table` throughout.** Emitted because `env.py` sets
   `render_as_batch` for SQLite. Correct as generated: SQLite cannot
   `ALTER TABLE ... ALTER COLUMN`, so the batch form rebuilds the table, and the
   load test, the chaos test and most of the unit suite all run on SQLite. A
   migration written without it works on Postgres -- the only database anyone
   reviews against -- and fails on the one the tests use.

`alembic check` in CI fails on drift between these models and this file, so
leaving a model change unmigrated is a red build rather than a surprise at deploy.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import backend.database.base  # noqa: F401  (registers UtcDateTime for the DDL below)


# revision identifiers, used by Alembic.
revision: str = '054a1ad5a350'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # autogenerated, reviewed -- see the module docstring
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=True),
    sa.Column('entity', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_order_id'), ['order_id'], unique=False)

    op.create_table('fraud_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('latency_ms', sa.Double(), nullable=False),
    sa.Column('decided_at', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0.0 AND score <= 1.0', name=op.f('ck_fraud_scores_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_scores')),
    sa.UniqueConstraint('event_id', name=op.f('uq_fraud_scores_event_id'))
    )
    with op.batch_alter_table('fraud_scores', schema=None) as batch_op:
        batch_op.create_index('ix_fraud_scores_band_decided', ['band', 'decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fraud_scores_order_id'), ['order_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', backend.database.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_notifications_unsent', ['sent_at', 'created_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('hold_reason', sa.Text(), nullable=True),
    sa.Column('fraud_score', sa.Double(), nullable=True),
    sa.Column('fraud_band', sa.String(length=16), nullable=True),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fraud_score IS NULL OR (fraud_score >= 0.0 AND fraud_score <= 1.0)', name=op.f('ck_orders_fraud_score_range')),
    sa.CheckConstraint('total_cents >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orders_idempotency_key'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index('ix_orders_status_created', ['status', 'created_at'], unique=False)

    op.create_table('processed_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('consumer_group', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=True),
    sa.Column('effect', sa.String(length=128), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=True),
    sa.Column('log_offset', sa.Integer(), nullable=True),
    sa.Column('applied_at', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_processed_events'))
    )
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_events_order_id'), ['order_id'], unique=False)
        batch_op.create_index('ix_processed_group_applied', ['consumer_group', 'applied_at'], unique=False)

    op.create_table('review_queue_items',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('sla_deadline', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', backend.database.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(status = 'pending') OR (decided_by IS NOT NULL AND decided_at IS NOT NULL)", name=op.f('ck_review_queue_items_decided_has_actor')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue_items')),
    sa.UniqueConstraint('order_id', name=op.f('uq_review_queue_items_order_id')),
    sa.UniqueConstraint('task_id', name=op.f('uq_review_queue_items_task_id'))
    )
    with op.batch_alter_table('review_queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_queue_items_sla_deadline'), ['sla_deadline'], unique=False)
        batch_op.create_index('ix_review_status_sla', ['status', 'sla_deadline'], unique=False)

    op.create_table('stock_reservations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('expires_at', backend.database.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('released_at', backend.database.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_reservations')),
    sa.UniqueConstraint('order_id', 'warehouse_id', name='uq_reservation_order_warehouse')
    )
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.create_index('ix_reservations_expiry', ['state', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_reservations_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('ships_international', sa.Boolean(), nullable=False),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses'))
    )
    op.create_table('inventory',
    sa.Column('warehouse_id', sa.String(length=32), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', backend.database.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('available = on_hand - reserved', name=op.f('ck_inventory_available_consistent')),
    sa.CheckConstraint('available >= 0', name=op.f('ck_inventory_available_non_negative')),
    sa.CheckConstraint('on_hand >= 0', name=op.f('ck_inventory_on_hand_non_negative')),
    sa.CheckConstraint('reserved >= 0', name=op.f('ck_inventory_reserved_non_negative')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warehouse_id', 'sku', name=op.f('pk_inventory'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_sku', ['sku'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=40), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('unit_price_cents >= 0', name=op.f('ck_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    sa.UniqueConstraint('order_id', 'sku', name='uq_order_items_order_sku')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # autogenerated, reviewed -- see the module docstring
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_sku')

    op.drop_table('inventory')
    op.drop_table('warehouses')
    with op.batch_alter_table('stock_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_reservations_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservations_order_id'))
        batch_op.drop_index(batch_op.f('ix_stock_reservations_expires_at'))
        batch_op.drop_index('ix_reservations_expiry')

    op.drop_table('stock_reservations')
    with op.batch_alter_table('review_queue_items', schema=None) as batch_op:
        batch_op.drop_index('ix_review_status_sla')
        batch_op.drop_index(batch_op.f('ix_review_queue_items_sla_deadline'))

    op.drop_table('review_queue_items')
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_index('ix_processed_group_applied')
        batch_op.drop_index(batch_op.f('ix_processed_events_order_id'))

    op.drop_table('processed_events')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status_created')
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_correlation_id'))

    op.drop_table('orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_unsent')
        batch_op.drop_index(batch_op.f('ix_notifications_order_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('fraud_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fraud_scores_order_id'))
        batch_op.drop_index('ix_fraud_scores_band_decided')

    op.drop_table('fraud_scores')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_order_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_correlation_id'))
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_created')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
